define NO_EXPORT = (65535, 65281);
define NO_ADVERTISE = (65535, 65282);
define NO_EXPORT_SUBCONFED = (65535, 65283);
define BLACKHOLE = (65535, 666);

define NCN_EXPORT_NO_EBGP = (MY_ASN, 100, 0);
define NCN_EXPORT_NO_IBGP = (MY_ASN, 100, 1);
define NCN_EXPORT_INTERNAL = (MY_ASN, 100, 2);
define NCN_EXPORT_ALL = (MY_ASN, 100, 3);

define NCN_FROM_DOWNSTREAM = (MY_ASN, 200, 0);
define NCN_FROM_UPSTREAM = (MY_ASN, 200, 1);
define NCN_FROM_PEER = (MY_ASN, 200, 3);

define NCN_REGION = (MY_ASN, 300, MY_REGION);

protocol bfd {
	interface "*" {
		interval 900ms;
		multiplier 4;
	};
}

function ebgp_downstream_export_filter() -> bool {
	if bgp_community ~ [ NO_EXPORT, NO_EXPORT_SUBCONFED, NO_ADVERTISE ] then reject;
	if bgp_large_community ~ [ NCN_EXPORT_NO_EBGP, NCN_EXPORT_INTERNAL ] then reject;
	bgp_large_community.add(NCN_REGION);
	if source = RTS_STATIC && proto = "ncn_agg" then return true;
	if source = RTS_BGP then return true;
	reject;
}

function ebgp_upstream_export_filter() -> bool {
	if bgp_community ~ [ NO_EXPORT, NO_EXPORT_SUBCONFED, NO_ADVERTISE ] then reject;
	if bgp_large_community ~ [ NCN_EXPORT_NO_EBGP, NCN_EXPORT_INTERNAL ] then reject;
	if (
		(bgp_large_community ~ [ NCN_EXPORT_ALL, NCN_FROM_DOWNSTREAM ] && NCN_REGION ~ bgp_large_community) ||
		(source = RTS_STATIC && proto = "static1")
	) then {
		bgp_large_community.add(NCN_REGION);
		return true;
	}
	reject;
}

function ebgp_peer_export_filter() -> bool {
	ebgp_upstream_export_filter();
	return true;
}

function ibgp_export_filter() -> bool {
	if NO_ADVERTISE ~ bgp_community then reject;
	if bgp_large_community ~ [ NCN_EXPORT_NO_IBGP ] then reject;
	if proto = "direct1" then {
		bgp_large_community.add(NCN_EXPORT_NO_EBGP);
		bgp_large_community.add(NCN_EXPORT_INTERNAL);
		bgp_large_community.add(NCN_REGION);
		return true;
	}
	if proto = "static1" then {
		bgp_large_community.add(NCN_REGION);
		return true;
	}
	if bgp_large_community ~ [ NCN_REGION, NCN_EXPORT_INTERNAL, NCN_EXPORT_ALL ,NCN_FROM_DOWNSTREAM ] then return true;
	reject;
}

function ebgp_import_filter() -> bool {
	if bgp_path.len > 64 then reject;
	if BLACKHOLE ~ bgp_community then dest = RTD_BLACKHOLE;
	case roa_check(roa6_cloudflare, net, bgp_path.last) {
		ROA_UNKNOWN: { bgp_local_pref = bgp_local_pref - 10; }
		ROA_INVALID: { reject; }
	}
	bgp_large_community.add(NCN_REGION);
	bgp_local_pref = bgp_local_pref + (64 - bgp_path.len);
	return true;
}

function ibgp_import_filter() -> bool {
	if bgp_path.len > 64 then reject;
	if BLACKHOLE ~ bgp_community then dest = RTD_BLACKHOLE;
	if bgp_large_community ~ [ NCN_REGION, NCN_EXPORT_INTERNAL, NCN_EXPORT_ALL, NCN_FROM_DOWNSTREAM ] then return true;
	reject;
}

template bgp ebgp_upstream_tpl {
	local as MY_ASN;
	long lived graceful restart on;
	ipv6 {
		next hop self;
		import filter {
			ebgp_import_filter();
			bgp_large_community.add(NCN_FROM_UPSTREAM);
			accept;
		};
		export where ebgp_upstream_export_filter();
	};
}

template bgp ebgp_downstream_tpl from ebgp_upstream_tpl {
	ipv6 {
		import filter {
			ebgp_import_filter();
			bgp_large_community.add(NCN_FROM_DOWNSTREAM);
			bgp_local_pref = bgp_local_pref + 2;
			accept;
		};
		export where ebgp_downstream_export_filter();
	};
}

template bgp ebgp_peer_tpl from ebgp_upstream_tpl {
	ipv6 {
		import filter {
			ebgp_import_filter();
			bgp_large_community.add(NCN_FROM_PEER);
			bgp_local_pref = bgp_local_pref + 1;
			accept;
		};
		export where ebgp_peer_export_filter();
	};
}


template bgp ibgp_full_tpl from ebgp_upstream_tpl {
	local MY_SADDR6 as MY_ASN;
	neighbor as MY_ASN;
	direct;
	bfd;
	ipv6 {
		import where ibgp_import_filter();
		export where ibgp_export_filter();
	};
}

template bgp ibgp_tpl from ibgp_full_tpl {
	ipv6 {
		export where ibgp_export_filter() && bgp_large_community ~ [ NCN_EXPORT_INTERNAL, NCN_EXPORT_ALL, NCN_FROM_DOWNSTREAM ];
	};
}
